// flow-typed signature: 78c9a4f5e4ddbc07e91f38206677fd0f
// flow-typed version: <<STUB>>/react-svg-sprite_v^1.0.8/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-sprite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-sprite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-sprite/svg-sprite' {
  declare module.exports: any;
}

declare module 'react-svg-sprite/symbol' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-sprite/svg-sprite.js' {
  declare module.exports: $Exports<'react-svg-sprite/svg-sprite'>;
}
declare module 'react-svg-sprite/symbol.js' {
  declare module.exports: $Exports<'react-svg-sprite/symbol'>;
}
