// flow-typed signature: 5aa797e9161fa149f0442291a7bfa980
// flow-typed version: <<STUB>>/react-svg_v^7.2.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg/cjs/react-svg.development' {
  declare module.exports: any;
}

declare module 'react-svg/cjs/react-svg.production.min' {
  declare module.exports: any;
}

declare module 'react-svg/es/react-svg' {
  declare module.exports: any;
}

declare module 'react-svg/umd/react-svg.development' {
  declare module.exports: any;
}

declare module 'react-svg/umd/react-svg.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg/cjs/react-svg.development.js' {
  declare module.exports: $Exports<'react-svg/cjs/react-svg.development'>;
}
declare module 'react-svg/cjs/react-svg.production.min.js' {
  declare module.exports: $Exports<'react-svg/cjs/react-svg.production.min'>;
}
declare module 'react-svg/es/react-svg.js' {
  declare module.exports: $Exports<'react-svg/es/react-svg'>;
}
declare module 'react-svg/index' {
  declare module.exports: $Exports<'react-svg'>;
}
declare module 'react-svg/index.js' {
  declare module.exports: $Exports<'react-svg'>;
}
declare module 'react-svg/umd/react-svg.development.js' {
  declare module.exports: $Exports<'react-svg/umd/react-svg.development'>;
}
declare module 'react-svg/umd/react-svg.production.min.js' {
  declare module.exports: $Exports<'react-svg/umd/react-svg.production.min'>;
}
