const ADD_SUCCESS = 'note/ADD_SUCCESS';
const DELETE_SUCCESS = 'note/DELETE_SUCCESS';
const TOGGLE_COMPLETED_SUCCESS = 'note/TOGGLE_COMPLETED_SUCCESS';
const CHANGE_FILTER = 'note/CHANGE_FILTER';

const FETCH_REQUEST = 'notes/FETCH_REQUEST';
const FETCH_SUCCESS = 'notes/FETCH_SUCCESS';
const FETCH_ERROR = 'notes/FETCH_ERROR';

export {
  ADD_SUCCESS,
  DELETE_SUCCESS,
  TOGGLE_COMPLETED_SUCCESS,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
